spring.application.name=url-shortener
max-shortening-tries=5

# Increasing this value may result in DB errors
short-url-length=7

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=dominik
spring.datasource.password=secret123
spring.jpa.hibernate.ddl-auto=none
